# Generated by Django 3.1.4 on 2021-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20210326_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='stock_shares',
            field=models.IntegerField(),
        ),
    ]
