# Generated by Django 3.1.4 on 2021-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20210327_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='stock_price',
            field=models.FloatField(default=0.0),
        ),
    ]
